// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt7a5e3CM8GwO4tNwHkvDMcw2JqAGbiQU',
    appId: '1:26394488999:web:37246647c784acb6f6ab82',
    messagingSenderId: '26394488999',
    projectId: 'insurance-1178e',
    authDomain: 'insurance-1178e.firebaseapp.com',
    storageBucket: 'insurance-1178e.firebasestorage.app',
    measurementId: 'G-PX8K7Y90B2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVELm6-egcrBnpjtw1tfE4snnauUpW9Rc',
    appId: '1:26394488999:android:4b12a8fdc381844ff6ab82',
    messagingSenderId: '26394488999',
    projectId: 'insurance-1178e',
    storageBucket: 'insurance-1178e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv6fyyVvAJ6ZIUdcBaihNh5D69Y6h9VJA',
    appId: '1:26394488999:ios:76b350321993cb50f6ab82',
    messagingSenderId: '26394488999',
    projectId: 'insurance-1178e',
    storageBucket: 'insurance-1178e.firebasestorage.app',
    iosBundleId: 'com.example.policy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv6fyyVvAJ6ZIUdcBaihNh5D69Y6h9VJA',
    appId: '1:26394488999:ios:76b350321993cb50f6ab82',
    messagingSenderId: '26394488999',
    projectId: 'insurance-1178e',
    storageBucket: 'insurance-1178e.firebasestorage.app',
    iosBundleId: 'com.example.policy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt7a5e3CM8GwO4tNwHkvDMcw2JqAGbiQU',
    appId: '1:26394488999:web:8102b56d050c4a97f6ab82',
    messagingSenderId: '26394488999',
    projectId: 'insurance-1178e',
    authDomain: 'insurance-1178e.firebaseapp.com',
    storageBucket: 'insurance-1178e.firebasestorage.app',
    measurementId: 'G-40X1F6B5C6',
  );
}
